bjw-s-labs/helm-charts

charts/other/app-template/Chart.yaml
charts/other/app-template/templates/common.yaml
charts/other/app-template/tests/addons/codeserver_test.yaml
charts/other/app-template/tests/addons/vpn_test.yaml
charts/other/app-template/tests/configmap/metadata_test.yaml
charts/other/app-template/tests/configmap/names_test.yaml
charts/other/app-template/tests/configmap/pod_metadata_test.yaml
charts/other/app-template/tests/container/envfrom_test.yaml
charts/other/app-template/tests/controller/metadata_daemonset_test.yaml
charts/other/app-template/tests/controller/metadata_deployment_test.yaml
charts/other/app-template/tests/controller/metadata_statefulset_test.yaml
charts/other/app-template/tests/controller/type_test.yaml
charts/other/app-template/tests/ingress/metadata_test.yaml
charts/other/app-template/tests/ingress/service_reference_test.yaml
charts/other/app-template/tests/misc/nameoverride_test.yaml
charts/other/app-template/tests/persistence/claimnames_test.yaml
charts/other/app-template/tests/persistence/types_test.yaml
charts/other/app-template/tests/pvc/metadata_test.yaml
charts/other/app-template/tests/pvc/names_test.yaml
charts/other/app-template/tests/service/metadata_test.yaml
charts/other/app-template/tests/service/names_test.yaml

feat(app-template): Set default nameOverride

---

.ci/mkdocs/mkdocs.yaml
docs/app-template/introduction.md
examples/flux/README.md
examples/flux/helmrelease.yaml
examples/flux/helmrepository.yaml
examples/helm/README.md
examples/helm/values.yaml
examples/kustomize/README.md
examples/kustomize/kustomization.yaml
examples/kustomize/values.yaml

**Benefits**
- fixes #
**Checklist**

docs(examples): Add some deployment examples

---

.github/workflows/charts-lint.yaml
.github/workflows/charts-release-ghpages.yaml
.github/workflows/charts-release.yaml
.github/workflows/pr-metadata.yaml
.github/workflows/pr-validate.yaml
charts/library/common/Chart.yaml
charts/library/common/templates/addons/vpn/_vpn.tpl
charts/library/common/values.yaml
charts/other/app-template/Chart.yaml
charts/other/app-template/tests/configmap/metadata_test.yaml
charts/other/app-template/tests/controller/metadata_daemonset_test.yaml
charts/other/app-template/tests/controller/metadata_deployment_test.yaml
charts/other/app-template/tests/controller/metadata_statefulset_test.yaml
charts/other/app-template/tests/ingress/metadata_test.yaml
charts/other/app-template/tests/pvc/metadata_test.yaml
charts/other/app-template/tests/service/metadata_test.yaml

- Update container versions
- Fixes VPN deprecation warning syntax
**Benefits**
- fixes #
**Checklist**

feat(common): Upcoming version placeholder

---

charts/library/common/Chart.yaml
charts/library/common/README.md
charts/library/common/templates/lib/service/_enabled_ports.tpl
charts/other/app-template/Chart.yaml
charts/other/app-template/tests/configmap/metadata_test.yaml
charts/other/app-template/tests/controller/metadata_daemonset_test.yaml
charts/other/app-template/tests/controller/metadata_deployment_test.yaml
charts/other/app-template/tests/controller/metadata_statefulset_test.yaml
charts/other/app-template/tests/ingress/metadata_test.yaml
charts/other/app-template/tests/pvc/metadata_test.yaml
charts/other/app-template/tests/route/metadata_test.yaml
charts/other/app-template/tests/secret/metadata_test.yaml
charts/other/app-template/tests/service/metadata_test.yaml

fix: Allow 0 enabledPorts

---

.ci/mkdocs/requirements.txt
charts/library/common/Chart.yaml
charts/library/common/templates/classes/_cronjob.tpl
charts/library/common/templates/render/_controller.tpl
charts/library/common/values.yaml

I started to use your library for most of my apps ( great job on this library btw! ). I have to run some of my applications as cronjobs, so i added a controller.type of deployment to generate a CronJob object. I tested the generated output to adhere to snyk's default rules.
no features removed
users will be able to run cronjobs of certain images to achive certain things
- fixes #

feat(common): add controller.type of cronjob

---

charts/library/common/templates/lib/controller/_volumes.tpl

fix: Fix invalid persistence type message

---

charts/library/common/Chart.yaml
charts/library/common/README.md
charts/library/common/templates/classes/_cronjob.tpl
charts/library/common/templates/classes/_route.tpl
charts/library/common/templates/lib/controller/_pod.tpl
charts/library/common/templates/lib/controller/_volumes.tpl
charts/library/common/templates/lib/routes/_primary.tpl
charts/library/common/templates/render/_controller.tpl
charts/library/common/templates/render/_routes.tpl
charts/library/common/values.yaml
charts/other/app-template/Chart.yaml
charts/other/app-template/ci/cronjob-values.yaml
charts/other/app-template/tests/configmap/metadata_test.yaml
charts/other/app-template/tests/controller/cronjob_test.yaml
charts/other/app-template/tests/controller/metadata_cronjob_test.yaml
charts/other/app-template/tests/controller/metadata_daemonset_test.yaml
charts/other/app-template/tests/controller/metadata_deployment_test.yaml
charts/other/app-template/tests/controller/metadata_statefulset_test.yaml
charts/other/app-template/tests/controller/type_test.yaml
charts/other/app-template/tests/ingress/metadata_test.yaml
charts/other/app-template/tests/pvc/metadata_test.yaml
charts/other/app-template/tests/route/metadata_test.yaml
charts/other/app-template/tests/route/service_reference_test.yaml
charts/other/app-template/tests/route/values_test.yaml
charts/other/app-template/tests/secret/metadata_test.yaml
charts/other/app-template/tests/service/metadata_test.yaml

- Fixed `sectionName` not being optional for gateway routes
- Fixed primary gateway route having incorrect name
- Fixed invalid persistence type message
- Added `cronjob` as `controller.type`
- Allow setting container restartPolicy
- fixes #

feat(common): Release version 1.2.0

---

charts/library/common/Chart.yaml
charts/library/common/templates/classes/_cronjob.tpl

fixing indentation for podAnnotations in the _cronjob.tpl. i started using the controller.type = cronjob together with a configMap and got an error for wrong intendation. It seems i didnt update this field properly with my inital PR. here's the fix for it
- fixes #

fix(common) wrong indentation in _cronjob.tpl

---

.github/workflows/charts-test.yaml
charts/library/common/Chart.yaml
charts/library/common/README.md
charts/library/common/templates/classes/_cronjob.tpl
charts/library/common/templates/lib/controller/_mainContainer.tpl
charts/library/common/values.yaml
charts/other/app-template/Chart.yaml
charts/other/app-template/tests/configmap/metadata_test.yaml
charts/other/app-template/tests/container/envfrom_test.yaml
charts/other/app-template/tests/controller/cronjob_test.yaml
charts/other/app-template/tests/controller/metadata_cronjob_test.yaml
charts/other/app-template/tests/controller/metadata_daemonset_test.yaml
charts/other/app-template/tests/controller/metadata_deployment_test.yaml
charts/other/app-template/tests/controller/metadata_statefulset_test.yaml
charts/other/app-template/tests/ingress/metadata_test.yaml
charts/other/app-template/tests/pvc/metadata_test.yaml
charts/other/app-template/tests/route/metadata_test.yaml
charts/other/app-template/tests/secret/metadata_test.yaml
charts/other/app-template/tests/service/metadata_test.yaml

- Cleaned leftover `secret` behavior under `envFrom`.
- Fixed indentation in cronjob component to allow podAnnotations
- Updated code-server image tag to 4.9.1
- fixes #94

feat(common): Release version 1.2.1

---

charts/library/common/Chart.yaml
charts/library/common/README.md
charts/library/common/templates/addons/code-server/_addon.tpl
charts/library/common/templates/addons/netshoot/_addon.tpl
charts/library/common/templates/addons/vpn/gluetun/_addon.tpl
charts/library/common/templates/lib/container/_probes.tpl
charts/library/common/templates/lib/controller/_mainContainer.tpl
charts/library/common/templates/lib/controller/_pod.tpl
charts/library/common/templates/values/_init.tpl
charts/library/common/values.yaml
charts/other/app-template/Chart.yaml
charts/other/app-template/tests/configmap/metadata_test.yaml
charts/other/app-template/tests/controller/metadata_cronjob_test.yaml
charts/other/app-template/tests/controller/metadata_daemonset_test.yaml
charts/other/app-template/tests/controller/metadata_deployment_test.yaml
charts/other/app-template/tests/controller/metadata_statefulset_test.yaml
charts/other/app-template/tests/ingress/metadata_test.yaml
charts/other/app-template/tests/pod/sidecars_test.yaml
charts/other/app-template/tests/pvc/metadata_test.yaml
charts/other/app-template/tests/route/metadata_test.yaml
charts/other/app-template/tests/secret/metadata_test.yaml
charts/other/app-template/tests/service/metadata_test.yaml
charts/other/app-template/tests/serviceMonitor/servicemonitor_test.yaml

- Don't render ports/probes when not required (triggered by #111)
- Renamed `additionalContainers` to `sidecars`. The former will however still continue to work for the time being.
- fixes #109
- fixes #111

feat(common): Release version 1.3.0

---

charts/library/common/Chart.yaml
charts/library/common/README.md
charts/library/common/templates/lib/chart/_notes.tpl
charts/library/common/templates/lib/container/_probes.tpl
charts/other/app-template/Chart.yaml
charts/other/app-template/tests/configmap/metadata_test.yaml
charts/other/app-template/tests/container/probes_test.yaml
charts/other/app-template/tests/controller/metadata_cronjob_test.yaml
charts/other/app-template/tests/controller/metadata_daemonset_test.yaml
charts/other/app-template/tests/controller/metadata_deployment_test.yaml
charts/other/app-template/tests/controller/metadata_statefulset_test.yaml
charts/other/app-template/tests/ingress/metadata_test.yaml
charts/other/app-template/tests/pvc/metadata_test.yaml
charts/other/app-template/tests/route/metadata_test.yaml
charts/other/app-template/tests/secret/metadata_test.yaml
charts/other/app-template/tests/service/metadata_test.yaml
charts/other/app-template/tests/serviceMonitor/servicemonitor_test.yaml

- Probes were rendered incorrectly when primary service port was a string.
- fixes #

feat(common): Release version 1.3.1

---

.github/workflows/charts-release-ghpages.yaml
.github/workflows/charts-release-oci.yaml
.github/workflows/charts-release.yaml
charts/library/common/Chart.yaml
charts/library/common/README.md
charts/library/common/templates/classes/_cronjob.tpl
charts/library/common/values.yaml
charts/other/app-template/Chart.yaml
charts/other/app-template/tests/configmap/metadata_test.yaml
charts/other/app-template/tests/controller/metadata_cronjob_test.yaml
charts/other/app-template/tests/controller/metadata_daemonset_test.yaml
charts/other/app-template/tests/controller/metadata_deployment_test.yaml
charts/other/app-template/tests/controller/metadata_statefulset_test.yaml
charts/other/app-template/tests/ingress/metadata_test.yaml
charts/other/app-template/tests/pvc/metadata_test.yaml
charts/other/app-template/tests/route/metadata_test.yaml
charts/other/app-template/tests/secret/metadata_test.yaml
charts/other/app-template/tests/service/metadata_test.yaml
charts/other/app-template/tests/serviceMonitor/servicemonitor_test.yaml

- Pod annotations were not indented enough when controller type was cronjob (#118)
- Updated code-server image tag to v4.10.0
- Updated netshoot image tag to v0.9
- fixes #

feat(common): Release version 1.3.2

---

charts/library/common/Chart.yaml
charts/library/common/README.md
charts/library/common/templates/classes/_cronjob.tpl
charts/library/common/values.yaml

Currently, CronJobs created from the common library must use the default `backoffLimit` of 6. This means jobs that fail will be attempted 6 times before they're considered to be failed. I use [borgmatic](https://torsion.org/borgmatic/) for backups in [gabe565/borgmatic](https://charts.gabe565.com/charts/borgmatic) which it has retries built in, so I'd like to be able to set this limit to 0 in case of failure.
CronJob `backoffLimit`
CronJobs will be able to be restarted a different number of times on failure.
None
- fixes #

feat(common): Add cron job backoff limit

---

charts/library/common/Chart.yaml
charts/library/common/templates/lib/controller/_pod.tpl
charts/library/common/values.yaml
charts/other/app-template/Chart.yaml
charts/other/app-template/tests/configmap/metadata_test.yaml
charts/other/app-template/tests/controller/metadata_cronjob_test.yaml
charts/other/app-template/tests/controller/metadata_daemonset_test.yaml
charts/other/app-template/tests/controller/metadata_deployment_test.yaml
charts/other/app-template/tests/controller/metadata_statefulset_test.yaml
charts/other/app-template/tests/ingress/metadata_test.yaml
charts/other/app-template/tests/pod/hostIPC_test.yaml
charts/other/app-template/tests/pod/hostPID_test.yaml
charts/other/app-template/tests/pvc/metadata_test.yaml
charts/other/app-template/tests/route/metadata_test.yaml
charts/other/app-template/tests/secret/metadata_test.yaml
charts/other/app-template/tests/service/metadata_test.yaml
charts/other/app-template/tests/serviceMonitor/servicemonitor_test.yaml

Add support for POD hostPID and hostIPC. Required for new Multus.
None
None
- POD hostPID
- POD hostIPC
None
- expose additional POD capabilities
- enable Multus chart
None
- fixes NA

feat(common) add hostPID and hostIPC

---

.github/workflows/charts-test.yaml
charts/library/common/Chart.yaml
charts/library/common/README.md
charts/library/common/templates/classes/_cronjob.tpl
charts/library/common/templates/classes/_deployment.tpl
charts/library/common/templates/lib/controller/_pod.tpl
charts/library/common/values.yaml
charts/other/app-template/Chart.yaml
charts/other/app-template/tests/configmap/metadata_test.yaml
charts/other/app-template/tests/controller/metadata_cronjob_test.yaml
charts/other/app-template/tests/controller/metadata_daemonset_test.yaml
charts/other/app-template/tests/controller/metadata_deployment_test.yaml
charts/other/app-template/tests/controller/metadata_statefulset_test.yaml
charts/other/app-template/tests/ingress/metadata_test.yaml
charts/other/app-template/tests/pod/hostIPC_test.yaml
charts/other/app-template/tests/pod/hostPID_test.yaml
charts/other/app-template/tests/pvc/metadata_test.yaml
charts/other/app-template/tests/route/metadata_test.yaml
charts/other/app-template/tests/secret/metadata_test.yaml
charts/other/app-template/tests/service/metadata_test.yaml
charts/other/app-template/tests/serviceMonitor/servicemonitor_test.yaml

- Add CronJob backoffLimit (#137)
- Add support for setting hostPID and hostIPC namespace (#140)
- Omit replicas field in Deployment if `null` is given (#134)
- Updated code-server image tag to v4.12.0
- Updated netshoot image tag to v0.10
- fixes #
CI has been updated to test against the latest Kubernetes patch versions for majors 1.22 through 1.27

feat: Release common version 1.5.0

---

charts/library/common/Chart.yaml
charts/library/common/templates/classes/_ingress.tpl
charts/library/common/values.yaml
charts/other/app-template/Chart.yaml
charts/other/app-template/tests/configmap/metadata_test.yaml
charts/other/app-template/tests/controller/metadata_cronjob_test.yaml
charts/other/app-template/tests/controller/metadata_daemonset_test.yaml
charts/other/app-template/tests/controller/metadata_deployment_test.yaml
charts/other/app-template/tests/controller/metadata_statefulset_test.yaml
charts/other/app-template/tests/ingress/metadata_test.yaml
charts/other/app-template/tests/ingress/tls_test.yaml
charts/other/app-template/tests/pvc/metadata_test.yaml
charts/other/app-template/tests/route/metadata_test.yaml
charts/other/app-template/tests/secret/metadata_test.yaml
charts/other/app-template/tests/service/metadata_test.yaml
charts/other/app-template/tests/serviceMonitor/servicemonitor_test.yaml

- Ingress secret name template is evaluated before deciding whether to omit it
- Updated code-server image tag to v4.13.0
- Updated netshoot image tag to v0.11
- Updated gluetun image tag to v3.34.3
- fixes #

feat: Release common version 1.5.1

---

.ci/repo-config.yaml
.github/renovate.json5
.github/workflows/pr-metadata.yaml
.github/workflows/pr-validate.yaml
charts/apps/k8s-ycl/.helmignore
charts/apps/k8s-ycl/Chart.yaml
charts/apps/k8s-ycl/templates/_helpers.tpl
charts/apps/k8s-ycl/templates/admissionregistration.yaml
charts/apps/k8s-ycl/templates/common.yaml
charts/apps/k8s-ycl/templates/pki.yaml
charts/apps/k8s-ycl/values.yaml

feat(k8s-ycl): Add

---

.ci/repo-config.yaml
charts/library/common-test/ci/advanced-values.yaml
charts/library/common-test/ci/basic-values.yaml
charts/library/common-test/ci/cronjob-values.yaml
charts/library/common-test/ci/no-service.yaml
charts/library/common-test/tests/container/volumemounts_test.yaml
charts/library/common-test/values.yaml
charts/other/app-template/Chart.yaml

feat(app-template): Release 2.0.0-beta.1

---

charts/other/app-template/Chart.yaml

feat(app-template): Bump to 2.0.0-beta.2

---

charts/library/common/Chart.yaml
charts/library/common/templates/lib/container/fields/_volumeMounts.tpl

feat(common): Release 2.0.0-beta.3

---

charts/other/app-template/Chart.yaml

feat(app-template): Bump to 2.0.0-beta.3

---

.github/workflows/docs-release.yaml
charts/library/common/Chart.yaml
charts/library/common/README.md
charts/library/common/templates/classes/_route.tpl
charts/library/common/values.yaml

Detects the Gateway API version available for each kind in the `route` object.
- fixes #
https://github.com/kubernetes-sigs/gateway-api/releases/tag/v0.8.0
Version `0.8.0` of Gateway API drops `v1alpha2` version for `Gateway`, `GatewayClass`, and `HTTPRoute`.

feat: Detect Gateway API version

---

charts/library/common/values.yaml

Made the comment above `controllers.main.containers.main.lifecycle` clearer as to what the spec is referring to, and add ref link to kubernetes.io docs

fix(library/common): clarify container lifecycle comment

---

.github/workflows/charts-release-ghpages.yaml
.github/workflows/charts-release.yaml
.github/workflows/tag-charts.yaml
charts/library/common-test/tests/container/volumemounts_test.yaml
charts/library/common-test/tests/persistence/volumes_test.yaml
charts/library/common/Chart.yaml
charts/library/common/README.md
charts/library/common/templates/lib/pod/fields/_volumes.tpl
charts/library/common/values.yaml
charts/other/app-template/Chart.yaml
charts/other/app-template/README.md

- Volumes did not render correctly across multiple controllers
- fixes #

feat(common): Release v2.0.3

---

charts/library/common/Chart.yaml
charts/library/common/templates/classes/_route.tpl

Simply adds gateway apis v1 support.
Some of the resources GA'ed
Allows us to be able to create v1 resources.
- HTTPRoute route is able to be created using the natural v1
- other's will follow as they are GA'ed (but currently this is the only one)
Gateways and GatewayClasses, which are not supported via the helm chart are the other two.
- Support of wider range of types, v1apha2 (which will eventually be removed)
- Support of v1beta
- Support of v1
None
None
- [-] Variables have been documented in the `values.yaml` file.

fix(common): add support for Gateway API v1

---

charts/library/common-test/ci/advanced-values.yaml
charts/library/common-test/tests/pod/container_order_test.yaml
charts/library/common-test/tests/pod/initcontainers_test.yaml
charts/library/common/Chart.yaml
charts/library/common/README.md
charts/library/common/templates/lib/chart/_getMapItemsWithKey.tpl
charts/library/common/templates/lib/pod/fields/_containers.tpl
charts/library/common/templates/lib/pod/fields/_initContainers.tpl
charts/library/common/values.yaml
charts/other/app-template/Chart.yaml
charts/other/app-template/README.md

- Add support for dependsOn to `initContainers` and `containers`.
Note that using `dependsOn` completely disables the `order` field within that controller.
🚨 The `order` field will be removed in v3. 🚨
- fixes #

feat(common): Release v2.2.0

---

charts/library/common-test/tests/service/port_protocols_test.yaml
charts/library/common/Chart.yaml
charts/library/common/templates/classes/_service.tpl
charts/library/common/values.yaml

As this impacts the modification of "service" everyone that has services would be able to add this.
Allows users to specify the Application Protocol available since k8s 1.20.
kubernetes.io/h2c -> http/2 over cleartext
kubernetes.io/ws -> websocket
kubernetes.io/wss -> websocket secure
are some examples
Helm chart value `appProtocol`
With Gateway APIs, it tells the Gateway APIs implementation (cilium) how to communicate with the application.
From K8s docs (App Protocol)[https://kubernetes.io/docs/concepts/services-networking/service/#application-protocol]
```
This is used as a hint for implementations to offer richer behavior for protocols that they understand. The value of this field is mirrored by the corresponding Endpoints and EndpointSlice objects.
```
N/A

feat(common): Kubernetes Service - App Protocol support

---

charts/library/common-test/tests/route/values_test.yaml
charts/library/common/Chart.yaml
charts/library/common/README.md
charts/library/common/templates/classes/_route.tpl
charts/library/common/values.yaml

Adds supports for Filters for both GRPC and HTTP Routes.
fixes support for matching with GRPC routes
matches for GRPCRoute
filters for HTTPRoute and GRPCRoute
- fixes #224

feat(gateway-apis): Support Filters for HTTPRoutes and GRPCRoutes

---

docs/app-template/index.md

Small description of why you would want to use the app-template and also mention kubesearch

chore: add more usage information for app-template

---

charts/apps/k8s-ycl/Chart.yaml
charts/library/common/Chart.yaml
charts/other/app-template/Chart.yaml
examples/flux/helmrelease.yaml
examples/helm/vaultwarden/values.yaml

update Chart.yaml and examples

---

charts/library/common-test/tests/container/workingdir_test.yaml
charts/library/common/Chart.yaml
charts/library/common/templates/lib/container/_spec.tpl
charts/library/common/values.yaml

Support `workingDir` for containers.
- fixes #

feat(common): Allow specifying `workingDir` for containers.

---

README.md

Update discord links to home-operations

docs(readme): Update discord links to home-operations

---

charts/other/app-template/Chart.yaml
charts/other/app-template/README.md
charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
charts/other/app-template/values.schema.json
docs/app-template/index.md

feat(app-template)!: Release app-template-3.0.0

---

charts/library/common-test/tests/chart/validations_test.yaml
charts/library/common-test/tests/container/probes_test.yaml
charts/library/common-test/tests/service/validations_test.yaml
charts/library/common/Chart.yaml
charts/library/common/README.md
charts/library/common/schemas/service.json
charts/library/common/templates/lib/chart/_validate.tpl
charts/library/common/templates/lib/controller/_getByIdentifier.tpl
charts/library/common/templates/lib/service/_primaryForController.tpl
charts/library/common/templates/lib/service/_validate.tpl
charts/library/common/templates/loader/_generate.tpl
charts/library/common/values.schema.json

- Fixed probes intermittently choosing the wrong service (#290, thanks @gabe565!)
- Prevent potential incorrect controller references
- fixes #289

fix(common): Release v3.0.3

---

charts/library/common-test/tests/ingress/values_test.yaml
charts/library/common/Chart.yaml
charts/library/common/templates/classes/_ingress.tpl
charts/library/common/values.yaml

Template the ingress annotations
My use case is to have variations of a chart with a unique title for gethomepage
Template the ingress annotations
Allows for template functions to be used in ingress annotations
Can't use any of {{ or }} out of the box. Not likely to be the case for annotations
- fixes #

feat: Template ingress annotations

---

charts/library/common-test/tests/container/field_stdin_test.yaml
charts/library/common-test/tests/container/field_tty_test.yaml
charts/library/common/Chart.yaml
charts/library/common/README.md
charts/library/common/templates/lib/container/_spec.tpl
charts/library/common/values.schema.json

fix(common): Remove trim from container stdin & tty fields (#340)

---

.github/workflows/charts-release-oci.yaml

It adds signing the oci published charts with keyless cosign. A lot of people use your app-template chart and it would be cool to be able to verify the origination in flux.
Added code and needed permissions in the oci chart publishing workflow.
Output of the successfully signed chart can be checked in the workflow log.
By adding the following to a helmrelease chart spec or an OCIRepository you can prevent the installation of corrupted charts.
```
verify:
provider: cosign
matchOIDCIdentity:
- issuer: "^https://token.actions.githubusercontent.com$"
subject: "^https://github.com/bjw-s/helm-charts.*$"
```
No
- fixes #

ci: Update charts-release-oci.yaml for keyless cosigning

---

charts/apps/k8s-ycl/Chart.yaml
charts/apps/k8s-ycl/README.md
charts/apps/k8s-ycl/values.schema.json
charts/other/app-template/Chart.yaml
charts/other/app-template/README.md
charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
charts/other/app-template/values.schema.json

feat: Bump common library to v3.4.0

---

charts/library/common-test/tests/pod/field_hostUsers_test.yaml
charts/library/common-test/tests/pod/metadata_annotations_test.yaml
charts/library/common-test/tests/pod/metadata_labels_test.yaml
charts/library/common/Chart.yaml
charts/library/common/README.md
charts/library/common/schemas/pod.json
charts/library/common/templates/lib/pod/_spec.tpl
charts/library/common/templates/lib/pod/metadata/_annotations.tpl
charts/library/common/templates/lib/pod/metadata/_labels.tpl
charts/library/common/values.schema.json
charts/library/common/values.yaml

- Add `hostUsers` field to pod spec for k8s clusters >= 1.29 (#363)
- Allow propagating global labels and annotations to Pod metadata
- fixes #

feat(common): Release common library 3.6.0

---

charts/library/common-test/tests/ingress/values_test.yaml
charts/library/common-test/tests/pod/field_hostUsers_test.yaml
charts/library/common/Chart.yaml
charts/library/common/README.md
charts/library/common/schemas/ingress.json
charts/library/common/schemas/k8s-api.json
charts/library/common/schemas/pod.json
charts/library/common/templates/classes/_ingress.tpl
charts/library/common/templates/lib/pod/_spec.tpl
charts/library/common/values.schema.json
charts/library/common/values.yaml

- Only add hostUsers when explicitly configured
- `hosts` should be an optional field for Ingress resources
- `defaultBackend` should be an object for Ingress resources
- fixes #366 
- fixes #368

fix(common): Release 3.6.1

---

.github/actions/charts-release-ghpages/action.yaml
.github/workflows/charts-release.yaml
charts/library/common/.helmignore

ci: Fix release pipeline

---

charts/library/common/Chart.yaml
charts/library/common/README.md
charts/library/common/templates/lib/routes/_getByIdentifier.tpl
charts/library/common/templates/lib/routes/_validate.tpl
charts/library/common/test-chart/unittests/route/field_backendRefs_test.yaml
charts/library/common/test-chart/unittests/route/validations_test.yaml
charts/library/common/test-chart/unittests/service/field_selector_test.yaml
charts/library/common/test-chart/unittests/service/validations_test.yaml
charts/library/common/values.schema.json
charts/other/app-template/Chart.yaml
charts/other/app-template/README.md
charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
charts/other/app-template/values.schema.json

fix(common): Release common-4.0.1

---

charts/library/common/Chart.yaml
charts/library/common/README.md
charts/library/common/templates/lib/pod/_getOption.tpl
charts/library/common/templates/lib/routes/_autoDetectService.tpl
charts/library/common/test-chart/unittests/pod/field_nodeSelector_test.yaml
charts/library/common/test-chart/unittests/route/field_backendRefs_test.yaml
charts/library/common/values.schema.json

- Fixed an edge-case bug where specifying a merge defaultPodOptionsStrategy could crash the chart.
- Fixed Route automatic service detection if there are no rules defined.
- fixes #

fix(common): Release v4.1.1

---

charts/other/app-template/Chart.yaml
charts/other/app-template/README.md
charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
charts/other/app-template/values.schema.json
examples/flux/helmrelease.yaml
examples/helm/home-assistant/values.yaml
examples/helm/qbittorrent/values.yaml
examples/helm/vaultwarden/values.yaml
examples/kustomize/kustomization.yaml
examples/kustomize/values.yaml

fix(app-template): Release v4.1.1

---

.taskfiles/charts.yaml
.taskfiles/install.yaml
Taskfile.yaml
charts/library/common/schemas/rbac.json
charts/library/common/templates/classes/_rolebinding.tpl
charts/library/common/templates/lib/rolebinding/_validate.tpl
charts/library/common/test-chart/unittests/_values/rbac_values.yaml
charts/library/common/test-chart/unittests/_values/rolebinding_values.yaml
charts/library/common/test-chart/unittests/rbac/rolebinding_test.yaml
charts/library/common/values.yaml

Developers using the AppTemplate in enterprise or homelab environments with OIDC authentication may want to support `User` and `Group` subjects in `RoleBinding` or `ClusterRoleBinding` resources. This allows access to be granted based on a per-OIDC group membership and/or OIDC user basis.
* Added support for `User` and `Group` subjects for `RoleBinding` and `ClusterRoleBinding` resources. Added relevant tests to ensure functionality.
* Created `install.yaml` Task File to ensure `cargo`, the `helm-unittest` plugin, and the latest `schematools-cli` are installed; ultimately used to make contributing easier.
* Updated the `values.yaml` file to include more example `subjects` for `RoleBinding` and `ClusterRoleBinding` resources.
* Enables developers who have OIDC in their cluster to provide …

feat: Added support for RoleBinding/ClusterRoleBinding Group and User subjects; added/updated Taskfiles to make contributor onboarding easier.

---

charts/other/app-template/Chart.yaml
charts/other/app-template/README.md
charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
charts/other/app-template/values.schema.json
examples/flux/helmrelease.yaml
examples/helm/home-assistant/values.yaml
examples/helm/qbittorrent/values.yaml
examples/helm/vaultwarden/values.yaml
examples/kustomize/kustomization.yaml
examples/kustomize/values.yaml

feat(app-template): Upgrade to 4.2.0
