bjw-s-labs/helm-charts

charts/library/common/Chart.yaml, charts/library/common/templates/classes/_service.tpl, charts/library/common/values.yaml
Allow services to use extra keys in selector
**Benefits**
authentik helm chart overrides the deployment template, and adds a component label. https://github.com/goauthentik/helm/blob/main/charts/authentik/templates/deployment.yaml#L19
This fix allows the service to target just the server instaed of both. recent versions of nginx ingress have trouble with selector label matches a pod with no ports (which the overridded template did)
since it parses, merges, then to yaml again, it should just work. Nothing else I could think of wouldn't be a breaking change.
see authentik helm chart
**Checklist**
=> feat(common): Allow services to use extra keys in selector

charts/library/common/Chart.yaml, charts/library/common/templates/_notes.tpl
NOTES generation inconsistently uses `$protocol` and `$prefix` to add the protocol to the output URL. This causes ingresses to always show as `http://...`. This PR removes the `$protocol` var and uses `$prefix` to match the behavior of NOTES when ingress is disabled.
**Benefits**
NOTES will give a more accurate deployment URL.
Slight change to NOTES output, which is currently always `http`.
N/A
**Checklist**
=> fix(common): Fix NOTES always showing ingress protocol as http

charts/library/common/Chart.yaml, charts/library/common/templates/_route.tpl, charts/library/common/templates/classes/_route.tpl, charts/library/common/templates/loader/_generate.tpl, charts/library/common/templates/render/_routes.tpl, charts/library/common/values.yaml, charts/other/app-template/Chart.yaml, charts/other/app-template/tests/configmap/metadata_test.yaml, charts/other/app-template/tests/controller/metadata_daemonset_test.yaml, charts/other/app-template/tests/controller/metadata_deployment_test.yaml, charts/other/app-template/tests/controller/metadata_statefulset_test.yaml, charts/other/app-template/tests/ingress/metadata_test.yaml, charts/other/app-template/tests/pvc/metadata_test.yaml, charts/other/app-template/tests/route/metadata_test.yaml, charts/other/app-template/tests/route/presence_test.yaml, charts/other/app-template/tests/route/service_reference_test.yaml, charts/other/app-template/tests/route/values_test.yaml, charts/other/app-template/tests/service/metadata_test.yaml
Adds support for [Gateway API Routes](https://gateway-api.sigs.k8s.io/) similar to ingresses currently.
**Benefits**
With this update people using Gateway API for networking are able to add routes for their services using this chart instead of having to add only the route for the service created by chart.
The idea was to handle this behavior similar to how Ingresses are handled currently by the chart.
Non really that I can think of, one caveat is that the Gateway API uses CRDs, so the user would need to install those first before using them with this chart.
N/A
N/A
**Checklist**
=> feat(common): add support for gateway api routes

.ci/mkdocs/requirements.txt, charts/library/common/templates/lib/container/_probes.tpl
`httpGet` was not rendered because we removed too many spaces.
=> fix(common): `httpGet` probes template failed to render

charts/library/common/Chart.yaml, charts/library/common/templates/classes/_route.tpl, charts/library/common/templates/lib/routes/_primary.tpl, charts/library/common/templates/render/_routes.tpl, charts/library/common/values.yaml, charts/other/app-template/Chart.yaml, charts/other/app-template/tests/configmap/metadata_test.yaml, charts/other/app-template/tests/controller/metadata_daemonset_test.yaml, charts/other/app-template/tests/controller/metadata_deployment_test.yaml, charts/other/app-template/tests/controller/metadata_statefulset_test.yaml, charts/other/app-template/tests/ingress/metadata_test.yaml, charts/other/app-template/tests/pvc/metadata_test.yaml, charts/other/app-template/tests/route/metadata_test.yaml, charts/other/app-template/tests/route/service_reference_test.yaml, charts/other/app-template/tests/route/values_test.yaml, charts/other/app-template/tests/secret/metadata_test.yaml, charts/other/app-template/tests/service/metadata_test.yaml
Fixed couple of issues regarding gateway routes, details below.
The primary route was named incorrectly and this resulted in it referencing the primary service incorrectly, creating a broken route.
The `sectionName` was picking up empty string as a default value if not provided instead of being skipped, this made the route invalid if this value wasn't provided.
Routes can be used with the above values left to default, currently one has to provide these to have correct behaviour.
=> fix(common) - fix incorrect route default values

charts/library/common/Chart.yaml, charts/library/common/README.md, charts/library/common/templates/classes/_cronjob.tpl
This PR fixes an incorrect indent for pod annotations when `controller.type` is `CronJob`. 
#99 increased this indent from 8 to 10, but this is still incorrect. Pod annotations need to be indented by 12 spaces.
- CronJob pod annotations indent increased from 10 to 12
- fixes #
Example:
```yaml
spec:
...
jobTemplate:
spec:
template:
metadata:
annotations:
checksum/config: 48e0fde9b8afe61e94fd56fbe74506b67f029101228afa451372412dcbd8d105
labels:
app.kubernetes.io/name: borgmatic
app.kubernetes.io/instance: borgmatic
```
=> fix(common): Increase CronJob pod annotations indent from 10 to 12

charts/library/common/Chart.yaml, charts/library/common/templates/lib/metadata/_podAnnotations.tpl, charts/other/app-template/tests/secret/pod_metadata_test.yaml
Reload pod on secrets change
None
None
When a secret is added/modified/deleted the pod is reloaded.
None
Pod always using latest secrets
Unneeded reloads when pod can use the new secret without reload
NA
=> [common] Reload pod on secret change

charts/library/common/Chart.yaml, charts/library/common/templates/lib/controller/_mainContainer.tpl
Quote the command and args strings to support multiline arguments.
Quote the `command` and `args` strings in the main container.
Without the quoting of the `command` and `args` strings, the following gives an error:
```yaml
command:
- "/bin/sh"
- "-c"
args: |
echo hello
echo world
```
The error (which is quite vague):
> Error: YAML parse error on cronjob/templates/render.yaml: error converting YAML to JSON: yaml: line 48: could not find expected ':'
`args: >` does work without this change, but that requires you to add semicolons to each line.
If someone manually quoted the `command` or `args` string, it will now be double quoted.
=> fix(common): quote command and args strings

charts/library/common/Chart.yaml, charts/library/common/templates/classes/_deployment.tpl, charts/library/common/values.yaml
When using a HorizontalPodAutoscaler, the "replicas" field must be omitted. As per the [Kubernetes documentation](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#replicas).
> If a [HorizontalPodAutoscaler](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/) (or any similar API for horizontal scaling) is managing scaling for a Deployment, don't set .spec.replicas.
This ensures the Deployment will not scale down when doing a (rolling) update of the Pods.
Omit `replicas` field in Deployment if `controller.replicas = null`.
This allows the use of a HorizontalPodAutoscaler in combination with the Deployment that this chart creates.
When specifying `replicas: null` or `replicas:` in the Kubernetes manifest, the default number of 1 Pod will be used. …
=> feat(common): omit replicas field in Deployment if null is given

charts/library/common/Chart.yaml, charts/library/common/templates/classes/_ingress.tpl, charts/other/app-template/Chart.yaml, charts/other/app-template/tests/ingress/tls_test.yaml
Evaluates the ingress TLS secret name as a template before deciding whether to include or or omit the `secretName` field.
Using an ingress TLS secret name template evaluating to an empty string resulted in the `secretName` field still being added to the ingress TLS config with an empty string value.
Allows using a template that may or may not cause the `secretName` field to be present in the Ingress TLS config.
I guess this takes away the ability to ever add the ingress TLS secret name as an empty string. But I'm not sure ever having that as empty string is a valid use case.
None
=> fix(common): evaluate ingress secret name before condition

docs/src/common-library/storage/types/nfs-share.md
Added `mountPath` to documentation.
This helps clarify where an NFS share will be mounted within a given Pod.
=> docs(common-library): Added mountPath field to NFS share

charts/library/common-test/tests/route/service_reference_test.yaml, charts/library/common/Chart.yaml, charts/library/common/templates/classes/_route.tpl, charts/library/common/templates/lib/routes/_validate.tpl
Moves some parts to validation ensuring that a route will not be created with incorrect parameters.
This also allows us to set a filter without a backend ref in case it goes directly to the Gateway for reprocessing
Using `RequestRedirect` is not allowed with `BackendRefs`. 
I added a check to validate this and fail if it's present.
=> bugfix(gateway-apis): Specific filters without BackendRefs

charts/library/common-test/tests/route/values_test.yaml, charts/library/common/Chart.yaml, charts/library/common/README.md, charts/library/common/templates/classes/_route.tpl, charts/library/common/values.yaml
Adds support for timeouts field in HTTPRoute
Support increasing the timeout before client timeout 499 or backendRequest timeout. See spec below.
[Route Timeout Spec](https://gateway-api.sigs.k8s.io/reference/spec/#gateway.networking.k8s.io/v1.HTTPRouteTimeouts)
When needing a fixed or more amount of time for backends to complete their requests this field allows people using route to send a long timeout so the request can complete without it being killed/chunked by the Gateway-API implementation
=> feat(gateway-api): add timeouts for httproute as per spec

charts/library/common-test/tests/controller/cronjob_test.yaml, charts/library/common/Chart.yaml, charts/library/common/templates/classes/_cronjob.tpl, charts/library/common/values.yaml
It is currently not possible to suspend the CronJob, even though Kubernetes supports this natively. This PR adds support for this option.
The suspend option defaults to `false` when omitted, so always setting `spec.suspend` could result in a dirty diffs even though functionally nothing changes. Therefore I've opted to only add it when explicitly set.
Adds the ability to suspend the CronJob as described here: https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/#schedule-suspension.
More feature complete common chart.
> When .spec.suspend changes from true to false on an existing CronJob without a starting deadline, the missed jobs are scheduled immediately.
The documentation recommends setting a starting deadline. The common chart already sets this by default: …
=> feat(common): add suspend option to CronJob controller

README.md, charts/library/common-test/ci/advanced-values.yaml, charts/library/common-test/ci/basic-values.yaml, charts/library/common-test/tests/_values/ingress_main_default_hosts.yaml, charts/library/common-test/tests/_values/service_main_default.yaml, charts/library/common-test/tests/ingress/presence_test.yaml, charts/library/common-test/tests/ingress/service_reference_test.yaml, charts/library/common-test/tests/ingress/values_test.yaml, charts/library/common/Chart.yaml, charts/library/common/README.md, charts/library/common/README.md.gotmpl, charts/library/common/schemas/ingress.json, charts/library/common/templates/classes/_ingress.tpl, charts/library/common/templates/lib/ingress/_validate.tpl, charts/library/common/values.schema.json, charts/library/common/values.yaml
Prepare the `common` library v3.0.0 release
Upgrade information can be found here: https://bjw-s.github.io/helm-charts/docs/app-template/#from-2xx-to-30x
- Added support for `restartPolicy` field on container level. This will allow the use of  https://kubernetes.io/docs/concepts/workloads/pods/sidecar-containers/.
- Added json-schema validation. (⚠️ see "Possible drawbacks" section)
- Allow referencing secrets and configMaps by identifier in persistence section
- **BREAKING 🚨**: Default objects (they used to be called `main`) have been commented out and will therefore no longer provide any (both expected and unexpected) default values.
- **BREAKING🚨**: `enableServiceLinks` is now disabled by default
- **BREAKING🚨**: Referencing services under Ingress paths has been separated in explicit …
=> feat(common)!: Release common-3.0.0

charts/library/common-test/tests/container/probes_test.yaml, charts/library/common/Chart.yaml, charts/library/common/templates/lib/service/_primaryForController.tpl
While upgrading from v2 to v3, I noticed probes will randomly choose service ports that use a different controller. This PR makes it so that services are only chosen for probes if they target the current controller.
Fixes `bjw-s.common.lib.service.primaryForController` choosing services that don't match the current controller.
- fixes #289
=> fix(common): Fix probes intermittently choosing the wrong service

charts/library/common-test/ci/advanced-values.yaml, charts/library/common-test/tests/rawResource/metadata_test.yaml, charts/library/common-test/tests/rawResource/values_test.yaml, charts/library/common/Chart.yaml, charts/library/common/README.md, charts/library/common/schemas/containers.json, charts/library/common/schemas/controllers.json, charts/library/common/schemas/rawResource.json, charts/library/common/schemas/service.json, charts/library/common/templates/classes/_rawResource.tpl, charts/library/common/templates/classes/_service.tpl, charts/library/common/templates/classes/_statefulset.tpl, charts/library/common/templates/lib/container/_spec.tpl, charts/library/common/templates/lib/rawResource/_validate.tpl, charts/library/common/templates/lib/rawResource/_valuesToObject.tpl, charts/library/common/templates/loader/_generate.tpl, charts/library/common/templates/render/_rawResources.tpl, charts/library/common/values.schema.json, charts/library/common/values.yaml
- Added `externalName` field to service schema.
- Always allow specifying `nodePort` field on service ports.
- Added support for specifying `rawResources`. This can be used to add any resources that are not supported by this chart. Check out the [chart schema](https://github.com/bjw-s/helm-charts/blob/common-3.3.0/charts/library/common/schemas/rawResource.json) and [tests](https://github.com/bjw-s/helm-charts/blob/common-3.3.0/charts/library/common-test/tests/rawResource/metadata_test.yaml) for an example of how to use this feature.
- Added `stdin` and `tty` fields to container spec.
- Added `persistentVolumeClaimRetentionPolicy` field to statefulset spec.
- fixes #338 
- fixes #339 
- fixes #330 
- fixes #326 
- fixes #333 
- fixes #319 
- fixes #314
- fixes #154 (I think?) 
- fixes #133
=> feat(common): v3.3.0

charts/library/common-test/tests/container/field_stdin_test.yaml, charts/library/common-test/tests/container/field_tty_test.yaml, charts/library/common/Chart.yaml, charts/library/common/README.md, charts/library/common/templates/lib/container/_spec.tpl, charts/library/common/values.schema.json
Remove `trim` filter from `stdin` & `tty` fields in containers spec.
Remove `trim` filter which errors while processing boolean `stdin` & `tty` fields in containers spec.
=> fix(common): Remove trim from container stdin & tty fields

charts/library/common/schemas/service.json, charts/library/common/templates/classes/_service.tpl
Added support for setting the loadBalancerClass introduced in Kubernetes 1.24
See: https://kubernetes.io/docs/concepts/services-networking/service/#load-balancer-class
Allows multiple different types of LBs to be used. Also allows LBs that need a class to be set to be used. (e.g. Cilium Node IPAM See: https://docs.cilium.io/en/latest/network/node-ipam/ )
I have not increased the chart version as I saw you're about to release 3.4.0
I have not added the variable to the values.yaml file as other variables of this depth are also not in the values yaml (e.g. loadBalancerIP)
=> feat(common): Add support for loadBalancerClass

charts/library/common-test/tests/pod/field_hostUsers_test.yaml, charts/library/common/Chart.yaml, charts/library/common/schemas/pod.json, charts/library/common/templates/lib/pod/_spec.tpl, charts/library/common/values.yaml
This adds the [`hostUsers`](https://kubernetes.io/docs/concepts/workloads/pods/user-namespaces/) field when the chart is deployed to a k8s cluster that is 1.29 or newer. It defaults to `true`, k8s' default value.
`hostUsers` field to pod spec
Users of the chart can now specify that pods should run in their own user namespace, rather than reusing the host user namespace. Pods can run as root with reduced risk of container escape or privilege escalation.
Requires k8s 1.29 or newer, as well as specific CRI versions and kernel versions. Setting this requires that several other fields (such as `hostPID`) are false.
=> feat: add `hostUsers` pod field for k8s 1.29 and newer

charts/library/common/Chart.yaml, charts/library/common/schemas/containers.json
Allow Specifying pullPolicy=Never.
Improve compatibility with tools like skaffold, where the container is built right before being started, and needs to not be pulled because it does not exist in any remote repository. Even specifying "IfNotPresent" can still result in some element in the chain trying to pull; which fails and halts the process of bringing the container up.
Allows more of the official/upstream options; supporting other use-cases we are both unaware of.
None that I am aware of.
^ Did those last two in a separate commit that can be removed if schema changes are not sufficient reason to bump the version number.
=> feat(common): support pullPolicy=Never in schema

docs/app-template/howto/environment-variables.md
Adds examples to documentation for environment variables
- Directly in container with `env`
- From a `ConfigMap`
- From a `Secret`
:x: 
:x: 
Added examples in documentation
:x: 
Better documentation
:x: 
:x: 
Just providing the example I was looking for in the docs after I made it.
Thanks for making and maintaining this excellent project! :rocket:
=> docs(app-template): add env examples
